### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by thehappycoder** [ccc13/etcd-rs#3]

**Comment by thehappycoder** [comment]
When I run `cargo run`, I get Segmentation Fault: 11.

I started removing some code to understand what's causing it and it all came down to these lines:
```
use etcd_rs::prelude::*;
use etcd_rs::Client;
```

**Comment by ccc13** [comment]
@thehappycoder I cannot reproduce the error if you don't paste the code you run. 😂 Is there any problem when you run the example code?
