### ISSUE TITLE
Return references instead of clones

### ISSUE THREAD

**Issue by azastrael** [ccc13/etcd-rs#6]
Hey :wave:!

I saw that you wrote `// FIXME perf` in the sources and it seems that those are all related to cloning data. May I ask why the methods don't return references, allowing to the library's users to clone the returned data if wanted? :smiley:

Thank you :heart:!

**Comment by ccc13** [comment]
Yes, it looks more flexible by allowing the user to clone the data if wanted. [rust-protobuf](https://github.com/stepancheg/rust-protobuf) offers various ways to access the data. There is an [example](https://github.com/ccc13/etcd-rs/blob/master/src/proto/auth.rs#L54-L75).
It seems we could export the above methods.

**Comment by ccc13** [comment]
Further discussion in #11
