### ISSUE TITLE
Support auto refresh token

### ISSUE THREAD

**Issue by Dreamacro** [ccc13/etcd-rs#89]
Currently, there are two types of parameters for etcd's auth_token, `simple` (the default) and jwt (recommended for production environments https://etcd.io/docs/v3.5/op-guide/configuration/#auth). These two modes require the functionality to refresh tokens in specific situations.

For `simple`, when the etcd server restarts, tonic returns an `Unauthenticated` status code, and the entire client cannot make any more requests after that.

For `jwt`, when the token's time limit exceeds the TTL (which is usually not very long), the entire client cannot make any more requests.

I looked at the code for `etcd-rs` and found that it does not perform any refreshes afterward besides obtaining a token when connecting for the first time. I also looked at the tonic interceptor trait and found that retrieving the response seems impossible.

In the etcd-go client, there is some code for refreshing the token.

https://github.com/etcd-io/etcd/blob/53b48bbd5795210af2620ac757d9529b34a09e48/client/v3/retry_interceptor.go#L273-L281

Therefore, I would like to request that the Unauthenticated status code be added to automatically refresh the token, or at the very least, provide a manual refresh method.

**Comment by clnv** [comment]
Thanks for reporting the issue. We could refresh the token automatically if user provide the username and password. And may be we should deprecate `connect_with_token`.

**Comment by Dreamacro** [comment]
Is there a plan to deal with this issue? I'm not familiar with tonic, and after looking at the tonic documentation I can't find an `interceptor` that gets the response

**Comment by clnv** [comment]
> Is there a plan to deal with this issue? I'm not familiar with tonic, and after looking at the tonic documentation I can't find an interceptor that gets the response

No, I haven't spent too much time on this project. However, I am willing to review the PR and assist with any necessary improvements. Thank you.
