### ISSUE TITLE
About grand_lease and watcher

### ISSUE THREAD

**Issue by bodypumper** [ccc13/etcd-rs#94]
## Prepared
etcd-rs  tag：1.0.1
docker: docker-compose[node 1, node 2, node3]
<img width="1060" alt="image" src="https://github.com/lodrem/etcd-rs/assets/44149782/a4254565-5016-4606-9cc9-4e4c98210282">

## Notice
I didn't use cancel watch, just test the ttl invoke delete event.

## Test Code
<img width="824" alt="image" src="https://github.com/lodrem/etcd-rs/assets/44149782/d41b9bd6-ef2d-4f34-a646-ac1e59475f5c">

#### 1：success
<img width="1159" alt="image" src="https://github.com/lodrem/etcd-rs/assets/44149782/e6d1a383-408f-4886-9b78-1b708e66b228">

#### 2: failure
<img width="1308" alt="image" src="https://github.com/lodrem/etcd-rs/assets/44149782/164a256c-7b6d-4721-8356-6dc43b7ea5d4">

**Comment by clnv** [comment]
Did you mean it fails randomly because the lease expires before putting the kv?

**Comment by clnv** [comment]
https://github.com/lodrem/etcd-rs/blob/9ba8ecf9cd93a0a27ab35f4e51dd8389bceaf2af/integration-tests/src/kv.rs#L37-L57
This is the exact same test case, right?

**Comment by bodypumper** [comment]
> Did you mean it fails randomly because the lease expires before putting the kv?



> This is the exact same test case, right?

yes it is.This is an accidental error in etcd cluster.
it's not happen when in single etcd service.
I guess it's due to the delay in synchronizing messages between clusters

**Comment by bodypumper** [comment]
What if I need to extend the lease to permanent?

**Comment by clnv** [comment]
no. you need to keep alive the lease.

```rust
    let lease = cli
        .grant_lease(Duration::from_secs(10))
        .await
        .expect("grant lease");
    cli.put(PutRequest::new("foo", "bar").lease(lease.id))
        .await
        .expect("put kv with lease");

    let mut keepalive = cli.keep_alive_for(lease.id).await.unwrap();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(Duration::from_secs(5));
        loop {
            interval.tick().await;
            let resp = keepalive.keep_alive().await.unwrap();
            println!("keeping alive: {:?}", resp);
        }
    });

```

**Comment by bodypumper** [comment]
> ```rust
> let mut keepalive = cli.keep_alive_for(lease.id).await.unwrap();
>     tokio::spawn(async move {
>         let mut interval = tokio::time::interval(Duration::from_secs(5));
>         loop {
>             interval.tick().await;
>             let resp = keepalive.keep_alive().await.unwrap();
>             println!("keeping alive: {:?}", resp);
>         }
>     });
> ```



> no. you need to keep alive the lease.
> 
> ```rust
>     let lease = cli
>         .grant_lease(Duration::from_secs(10))
>         .await
>         .expect("grant lease");
>     cli.put(PutRequest::new("foo", "bar").lease(lease.id))
>         .await
>         .expect("put kv with lease");
> 
>     let mut keepalive = cli.keep_alive_for(lease.id).await.unwrap();
>     tokio::spawn(async move {
>         let mut interval = tokio::time::interval(Duration::from_secs(5));
>         loop {
>             interval.tick().await;
>             let resp = keepalive.keep_alive().await.unwrap();
>             println!("keeping alive: {:?}", resp);
>         }
>     });
> ```

So it's necessary to keep-alive regularly, right?
<img width="770" alt="image" src="https://github.com/lodrem/etcd-rs/assets/44149782/81539d75-37a4-4bfa-9559-c376029bb891">

**Comment by clnv** [comment]
yep

**Comment by bodypumper** [comment]
> yep

thanks
i have a question about directory. What‘s the way to create some directories ?
i want to create some directories and create some keys in it.

**Comment by clnv** [comment]
use kv API instead.

**Comment by bodypumper** [comment]
> use kv API instead.

ok
