### ISSUE TITLE
About create directories with KV API

### ISSUE THREAD

**Issue by bodypumper** [ccc13/etcd-rs#95]
What‘s the way to create some directories ?
i want to create some directories and create some keys in it.
i try to  use kv api to implement it but not work.
Do you have any examples？

**Comment by clnv** [comment]
There is no directory in etcd v3 API. You should use KV API with `prefix` or so.
https://github.com/lodrem/etcd-rs/blob/9ba8ecf9cd93a0a27ab35f4e51dd8389bceaf2af/examples/kv.rs#L37C37-L40
